# Auto-generated gender lookup from german_names_gender.md
# Maps full MP names to gender

GENDER_LOOKUP = {
    '-----------': '---------',
    'abdi, sanae': 'female',
    'abraham, knut': 'male',
    'achelwilm, doris': 'female',
    'achim köhler': 'male',
    'adam balten': 'male',
    'adis ahmetović': 'male',
    'adrian grasse': 'male',
    'aeikens, anna': 'female',
    'agnes conrad': 'female',
    'agnieszka brugger': 'female',
    'ahmetović, adis': 'male',
    'akbulut, gökay': 'male',
    'aken, jan van': 'male',
    'al-wazir, tarek': 'male',
    'alabali radovan, reem': 'female',
    'albani, stephan': 'male',
    'albert rupprecht': 'male',
    'alexander arpaschi': 'male',
    'alexander dobrindt': 'male',
    'alexander engelhard': 'male',
    'alexander hoffmann': 'male',
    'alexander jordan': 'male',
    'alexander radwan': 'male',
    'alexis l. giersch': 'unknown',
    'alhamwi, dr. alaa': 'unknown',
    'alois rainer': 'male',
    'altenkamp, norbert maria': 'male',
    'amthor, philipp': 'male',
    'amtsberg, luise': 'female',
    'andrea lindholz': 'female',
    'andreas audretsch': 'male',
    'andreas bleck': 'male',
    'andreas jung': 'male',
    'andreas mattfeldt': 'male',
    'andreas mayer': 'male',
    'andreas paul': 'male',
    'andreas schwarz': 'male',
    'anette kramme': 'female',
    'angela rudzka': 'female',
    'angelika glöckner': 'female',
    'anja karliczek': 'female',
    'anna aeikens': 'female',
    'annalena baerbock': 'female',
    'anne janssen': 'female',
    'anne könig': 'female',
    'anne-mieke bremer': 'female',
    'annika klose': 'female',
    'ansgar heveling': 'male',
    'armin laschet': 'male',
    'arndt, dr. michael': 'male',
    'arne raue': 'male',
    'arpaschi, alexander': 'male',
    'artur auernhammer': 'male',
    'asar, ayse': 'female',
    'asghari, prof. dr. reza': 'male',
    'ataoğlu, tijen': 'female',
    'ates gürpinar': 'male',
    'audretsch, andreas': 'male',
    'auernhammer, artur': 'male',
    'aumer, peter': 'male',
    'axel knoerig': 'male',
    'axel müller': 'male',
    'ayse asar': 'female',
    'babendererde, dr. cornell-anette': 'female',
    'bachmann, carolin': 'female',
    'badum, lisa': 'female',
    'baerbock, annalena': 'female',
    'baldy, daniel': 'male',
    'balten, adam': 'male',
    'banaszak, felix': 'male',
    'bareiß, thomas': 'male',
    'bartol, sören': 'male',
    'bartsch, dr. dietmar': 'male',
    'bas, bärbel': 'female',
    'bastian ernst': 'male',
    'bauer, marcel': 'male',
    'baum, dr. christina': 'female',
    'baumann, dr. bernd': 'male',
    'baumgartner, günter': 'male',
    'beck, katharina': 'female',
    'becker, carsten': 'male',
    'becker, desiree': 'female',
    'beek, sascha van': 'unknown',
    'behrens, jens': 'male',
    'benedikt büdenbender': 'male',
    'benner, lukas': 'male',
    'bernd rützel': 'male',
    'bernd schattner': 'male',
    'bernd schuhmann': 'male',
    'bernhard, marc': 'male',
    'bernstein, melanie': 'female',
    'bessin, birgit': 'female',
    'bettermann, daniel': 'male',
    'bettina hagedorn': 'female',
    'bettina lugk': 'female',
    'beutin, lorenz gösta': 'male',
    'beyer, peter': 'male',
    'biadacz, marc': 'male',
    'bilger, steffen': 'male',
    'bilic, florian': 'male',
    'birghan, dr. christoph': 'male',
    'birgit bessin': 'female',
    'blankenburg, jakob': 'male',
    'bleck, andreas': 'male',
    'bloch, joachim': 'male',
    'blos, dr. michael': 'male',
    'bochmann, rené': 'male',
    'bock, violetta': 'female',
    'bodin, leif erik': 'male',
    'bodo ramelow': 'male',
    'boehringer, peter': 'male',
    'bohnhof, peter': 'male',
    'bollmann, gereon': 'male',
    'bollmann, hendrik': 'male',
    'borchardt, simone': 'female',
    'boris gamanov': 'male',
    'boris mijatović': 'male',
    'boris pistorius': 'male',
    'bosbach, caroline': 'female',
    'bosch, jorrit': 'male',
    'bouffier, frederik': 'male',
    'braga, torben': 'male',
    'brand (fulda), michael': 'male',
    'brandes, dirk': 'male',
    'brandl, dr. reinhard': 'male',
    'brandner, stephan': 'male',
    'brantner, dr. franziska': 'female',
    'breher, silvia': 'female',
    'bremer, anne-mieke': 'female',
    'brinkhaus, ralph': 'male',
    'brinkmann, lutz': 'male',
    'britta haßelmann': 'female',
    'brodesser, dr. carsten': 'male',
    'broßart, victoria': 'female',
    'brucker, erhard': 'male',
    'brugger, agnieszka': 'female',
    'bröhr, dr. marlon': 'male',
    'brückner, maik': 'male',
    'bury, dr. yannick': 'male',
    'bär, dorothee': 'female',
    'bär, karl': 'male',
    'bärbel bas': 'female',
    'böttger, janina': 'female',
    'büdenbender, benedikt': 'male',
    'bühl, marcus': 'male',
    'bünger, clara': 'female',
    'cademartori, isabel': 'female',
    'cansin köktürk': 'female',
    'caren lay': 'female',
    'carina schießl': 'female',
    'carl-philipp sassenrath': 'male',
    'carolin bachmann': 'female',
    'caroline bosbach': 'female',
    'carsten becker': 'male',
    'carsten körber': 'male',
    'carsten müller': 'male',
    'carsten schneider (erfurt)': 'male',
    'carstensen, sandra': 'female',
    'castellucci, prof. dr. lars': 'male',
    'catarina dos santos-wintz': 'female',
    'cem ince': 'male',
    'cezanne, jörg': 'male',
    'chantal kopf': 'female',
    'charlotte antonia neuhäuser': 'female',
    'christian douglas': 'male',
    'christian görke': 'male',
    'christian haase': 'male',
    'christian hirte': 'male',
    'christian moser': 'male',
    'christian reck': 'male',
    'christoph frauenpreiß': 'male',
    'christoph grimm': 'male',
    'christoph schmid': 'male',
    'christopher drößler': 'male',
    'chrupalla, tino': 'male',
    'clara bünger': 'female',
    'claudia moll': 'female',
    'claudia müller': 'female',
    'claudia roth': 'female',
    'connemann, gitta': 'female',
    'conrad, agnes': 'female',
    'corinna rüffer': 'female',
    'coße, jürgen': 'male',
    'curio, dr. gottfried': 'male',
    'dagmar schmidt': 'female',
    'dahler, wolfgang': 'male',
    'dahmen, dr. janosch': 'male',
    'daniel baldy': 'male',
    'daniel bettermann': 'male',
    'daniel kölbl': 'male',
    'daniel rinkert': 'male',
    'daniela ludwig': 'female',
    'daniela rump': 'female',
    'danny meiners': 'unknown',
    'david gregosz': 'male',
    'david schliesing': 'male',
    'deborah düring': 'female',
    'demir, hakan': 'male',
    'demuth, ellen': 'female',
    'denis pauli': 'male',
    'denise loop': 'female',
    'dennis rohde': 'male',
    'desiree becker': 'female',
    'detzer, dr. sandra': 'female',
    'diana herbstreuth': 'female',
    'dieren, jan': 'male',
    'dietz, thomas': 'male',
    'dilcher, esther': 'female',
    'dillschneider, jeanne': 'female',
    'dirk brandes': 'male',
    'dittmar, sabine': 'female',
    'dobrindt, alexander': 'male',
    'donth, michael': 'male',
    'doris achelwilm': 'female',
    'dorn, dr. florian': 'male',
    'dorothee bär': 'female',
    'douglas, christian': 'male',
    'dr. alaa alhamwi': 'unknown',
    'dr. alexander gauland': 'male',
    'dr. andrea lübcke': 'female',
    'dr. andreas lenz': 'male',
    'dr. anja reinalter': 'female',
    'dr. anna lührmann': 'female',
    'dr. anna rathert': 'female',
    'dr. anton hofreiter': 'male',
    'dr. bernd baumann': 'male',
    'dr. bärbel kofler': 'female',
    'dr. carsten brodesser': 'male',
    'dr. carsten linnemann': 'male',
    'dr. christiane schenderlein': 'female',
    'dr. christina baum': 'female',
    'dr. christoph birghan': 'male',
    'dr. christoph ploß': 'male',
    'dr. christos pantazis': 'male',
    'dr. cornell-anette babendererde': 'female',
    'dr. david preisendanz': 'male',
    'dr. dietmar bartsch': 'male',
    'dr. fabian fahl': 'male',
    'dr. florian dorn': 'male',
    'dr. franziska brantner': 'female',
    'dr. franziska kersten': 'female',
    'dr. georg kippels': 'male',
    'dr. gottfried curio': 'male',
    'dr. gregor gysi': 'male',
    'dr. götz frömming': 'male',
    'dr. hendrik hoppenstedt': 'male',
    'dr. hülya düber': 'female',
    'dr. inge gräßle': 'female',
    'dr. irene mihalic': 'female',
    'dr. jan-marco luczak': 'male',
    'dr. jan-niclas gesenhues': 'male',
    'dr. janosch dahmen': 'male',
    'dr. johannes fechner': 'male',
    'dr. jonas geissler': 'male',
    'dr. kirsten kappert-gonther': 'female',
    'dr. konrad körner': 'male',
    'dr. konstantin von notz': 'male',
    'dr. lena gumnior': 'female',
    'dr. malte kaufmann': 'male',
    'dr. markus reichel': 'male',
    'dr. marlon bröhr': 'male',
    'dr. martin plum': 'male',
    'dr. mathias middelberg': 'male',
    'dr. matthias miersch': 'male',
    'dr. maximilian krah': 'male',
    'dr. med. paula piechotta': 'female',
    'dr. med. stephan pilsinger': 'male',
    'dr. michael arndt': 'male',
    'dr. michael blos': 'male',
    'dr. michael espendiller': 'male',
    'dr. michael meister': 'male',
    'dr. moritz heuberger': 'male',
    'dr. nils schmid': 'male',
    'dr. nina scheer': 'female',
    'dr. norbert röttgen': 'male',
    'dr. ophelia nick': 'female',
    'dr. ottilie klein': 'female',
    'dr. paul schmidt': 'male',
    'dr. philipp rottwilm': 'male',
    'dr. rainer kraft': 'male',
    'dr. rainer rothfuß': 'male',
    'dr. reinhard brandl': 'male',
    'dr. robert habeck': 'male',
    'dr. rolf mützenich': 'male',
    'dr. sandra detzer': 'female',
    'dr. saskia ludwig': 'female',
    'dr. sebastian schäfer': 'male',
    'dr. silke launert': 'female',
    'dr. stefan korbach': 'male',
    'dr. stefan nacke': 'male',
    'dr. tanja machalet': 'female',
    'dr. thomas gebhart': 'male',
    'dr. thomas pauls': 'male',
    'dr. thorsten rudolph': 'male',
    'dr. wiebke esdar': 'female',
    'dr. yannick bury': 'male',
    'dr. zoe mayer': 'female',
    'droßmann, falko': 'male',
    'dröge, katharina': 'female',
    'drößler, christopher': 'male',
    'dunja kreiser': 'female',
    'durz, hansjörg': 'male',
    'dzienus, timon': 'male',
    'döring, felix': 'male',
    'düber, dr. hülya': 'female',
    'düring, deborah': 'female',
    'ebenberger, tobias': 'male',
    'ebmeyer, joachim': 'male',
    'ebner, harald': 'male',
    'eckert, leon': 'male',
    'edelhäußer, ralph': 'male',
    'edgar naujok': 'male',
    'edis, mirze': 'unknown',
    'ehm, lars': 'male',
    'eichwede, sonja': 'female',
    'eißing, mandy': 'female',
    'elisabeth kaiser': 'female',
    'ellen demuth': 'female',
    'emmerich, marcel': 'male',
    'engelhard, alexander': 'male',
    'englhardt-kopf, martina': 'female',
    'enrico komning': 'male',
    'erhard brucker': 'male',
    'erndl, thomas': 'male',
    'ernst, bastian': 'male',
    'esdar, dr. wiebke': 'female',
    'esken, saskia': 'female',
    'espendiller, dr. michael': 'male',
    'esra limbacher': 'female',
    'esther dilcher': 'female',
    'fabian gramling': 'male',
    'fabian jacobi': 'male',
    'faeser, nancy': 'female',
    'fahl, dr. fabian': 'male',
    'falko droßmann': 'male',
    'fechner, dr. johannes': 'male',
    'fehre, micha': 'male',
    'feiler, uwe': 'male',
    'felix banaszak': 'male',
    'felix döring': 'male',
    'felix schreiner': 'male',
    'felser, peter': 'male',
    'ferat koçak': 'male',
    'feser, jan': 'male',
    'fetsch, thomas': 'male',
    'fey, katrin': 'female',
    'fiedler, sebastian': 'male',
    'filiz polat': 'female',
    'finger, hauke': 'male',
    'fischer, simone': 'female',
    'florian bilic': 'male',
    'florian hahn': 'male',
    'florian müller': 'male',
    'florian oest': 'male',
    'florian oßner': 'male',
    'foullong, uwe': 'male',
    'frank junge': 'male',
    'frank schwabe': 'male',
    'franziska hoppermann': 'female',
    'frauenpreiß, christoph': 'male',
    'frauke heiligenstadt': 'female',
    'frederik bouffier': 'male',
    'frei, thorsten': 'male',
    'friedrich merz': 'male',
    'frieser, michael': 'male',
    'fritz güntzler': 'male',
    'frohnmaier, markus': 'male',
    'frömming, dr. götz': 'male',
    'färber, hermann': 'male',
    'gabriela heinrich': 'female',
    'galla, rainer': 'male',
    'gamanov, boris': 'male',
    'gambir, schahina': 'female',
    'gastel, matthias': 'male',
    'gauland, dr. alexander': 'male',
    'gebel, kathrin': 'female',
    'gebhard, wilhelm': 'male',
    'gebhart, dr. thomas': 'male',
    'geissler, dr. jonas': 'male',
    'gennburg, katalin': 'female',
    'georg günther': 'male',
    'georg schroeter': 'male',
    'gereon bollmann': 'male',
    'gerold otten': 'male',
    'gerrit huy': 'male',
    'gerster, martin': 'male',
    'gesenhues, dr. jan-niclas': 'male',
    'giersch, alexis l.': 'unknown',
    'gitta connemann': 'female',
    'glaser, vinzenz': 'male',
    'gläser, ronald': 'male',
    'glöckner, angelika': 'female',
    'gnauck, hannes': 'male',
    'gohlke, nicole': 'female',
    'gottschalk, kay': 'unknown',
    'goßner, hans-jürgen': 'male',
    'gramling, fabian': 'male',
    'grasse, adrian': 'male',
    'grau, prof. dr. armin': 'male',
    'gregosz, david': 'male',
    'griese, kerstin': 'female',
    'grimm, christoph': 'male',
    'groß, rainer': 'male',
    'gräßle, dr. inge': 'female',
    'gumnior, dr. lena': 'female',
    'gunther krichbaum': 'male',
    'gutting, olav': 'male',
    'gysi, dr. gregor': 'male',
    'gökay akbulut': 'male',
    'göring-eckardt, katrin': 'female',
    'görke, christian': 'male',
    'güler, serap': 'female',
    'günter baumgartner': 'male',
    'günther, georg': 'male',
    'güntzler, fritz': 'male',
    'gürpinar, ates': 'male',
    'haase, christian': 'male',
    'habeck, dr. robert': 'male',
    'hagedorn, bettina': 'female',
    'hahn, florian': 'male',
    'hahn, prof. dr. ingo': 'male',
    'hain, heiko': 'male',
    'haise, lars': 'male',
    'hakan demir': 'male',
    'hakverdi, metin': 'male',
    'hanker, mirco': 'male',
    'hannes gnauck': 'male',
    'hans koller': 'male',
    'hans-jürgen goßner': 'male',
    'hansjörg durz': 'male',
    'harald ebner': 'male',
    'harald orthey': 'male',
    'hardt, jürgen': 'male',
    'hartmann, sebastian': 'male',
    'hauer, matthias': 'male',
    'haug, jochen': 'male',
    'hauke finger': 'male',
    'haßelmann, britta': 'female',
    'heidi reichinnek': 'female',
    'heike heubach': 'female',
    'heiko hain': 'male',
    'heil, hubertus': 'male',
    'heil, mechthild': 'female',
    'heiligenstadt, frauke': 'female',
    'heinrich koch': 'male',
    'heinrich, gabriela': 'female',
    'heitmann, linda': 'female',
    'helferich, matthias': 'male',
    'helfrich, mark': 'male',
    'helge limburg': 'male',
    'helge lindh': 'male',
    'helmut kleebank': 'male',
    'hemmelgarn, udo theodor': 'male',
    'hendrik bollmann': 'male',
    'henning otte': 'male',
    'henning rehbaum': 'male',
    'henri schmidt': 'male',
    'henrichmann, marc': 'male',
    'henze, stefan': 'male',
    'herbstreuth, diana': 'female',
    'hermann färber': 'male',
    'hermeier, mareike': 'female',
    'heselhaus, nadine': 'female',
    'hess, martin': 'male',
    'hess, nicole': 'female',
    'heubach, heike': 'female',
    'heuberger, dr. moritz': 'male',
    'heveling, ansgar': 'male',
    'hierl, susanne': 'female',
    'hiller, prof. dr. matthias': 'male',
    'hilmer, olaf': 'male',
    'hilse, karsten': 'male',
    'hirte, christian': 'male',
    'hoffmann, alexander': 'male',
    'hoffmann, philip m. a.': 'male',
    'hofreiter, dr. anton': 'male',
    'holger mann': 'male',
    'holm, leif-erik': 'male',
    'hoppenstedt, dr. hendrik': 'male',
    'hoppermann, franziska': 'female',
    'hose, michael': 'male',
    'hostert, jasmina': 'female',
    'hoß, luke': 'male',
    'hubertus heil': 'male',
    'hubertz, verena': 'female',
    'huy, gerrit': 'male',
    'höchst, nicole': 'female',
    'ina latendorf': 'female',
    'ince, cem': 'male',
    'ines schwerdtner': 'female',
    'iris nieland': 'female',
    'isabel cademartori': 'female',
    'isabel mackensen-geis': 'female',
    'jacobi, fabian': 'male',
    'jakob blankenburg': 'male',
    'jamila schäfer': 'female',
    'jan dieren': 'male',
    'jan feser': 'male',
    'jan köstering': 'male',
    'jan metzler': 'male',
    'jan ralf nolte': 'male',
    'jan van aken': 'male',
    'jan wenzel schmidt': 'male',
    'jan-wilhelm pohlmann': 'male',
    'janich, steffen': 'male',
    'janina böttger': 'female',
    'janssen, anne': 'female',
    'jarzombek, thomas': 'male',
    'jasmina hostert': 'female',
    'jeanne dillschneider': 'female',
    'jens behrens': 'male',
    'jens lehmann': 'male',
    'jens peick': 'male',
    'joachim bloch': 'male',
    'joachim ebmeyer': 'male',
    'jochen haug': 'male',
    'johann martel': 'male',
    'johann saathoff': 'male',
    'johannes rothenberger': 'male',
    'johannes schraps': 'male',
    'johannes schätzl': 'male',
    'jordan, alexander': 'male',
    'jorrit bosch': 'male',
    'josef oster': 'male',
    'josephine ortleb': 'female',
    'joswig, julian': 'male',
    'julia klöckner': 'female',
    'julia schneider': 'female',
    'julian joswig': 'male',
    'julian schmidt': 'male',
    'jung, andreas': 'male',
    'junge, frank': 'male',
    'jörg cezanne': 'male',
    'jörn könig': 'male',
    'jünger, robin': 'unknown',
    'jürgen coße': 'male',
    'jürgen hardt': 'male',
    'jürgen koegel': 'male',
    'kaczmarek, oliver': 'male',
    'kaddor, lamya': 'female',
    'kaiser, elisabeth': 'female',
    'kaminski, maren': 'female',
    'kappe, nicklas': 'male',
    'kappert-gonther, dr. kirsten': 'female',
    'karaahmetoäÿlu, macit': 'male',
    'karl bär': 'male',
    'karliczek, anja': 'female',
    'karoline otte': 'female',
    'karsten hilse': 'male',
    'katalin gennburg': 'female',
    'katharina beck': 'female',
    'katharina dröge': 'female',
    'kathrin gebel': 'female',
    'kathrin michel': 'female',
    'katja mast': 'female',
    'katrin fey': 'female',
    'katrin göring-eckardt': 'female',
    'kaufmann, dr. malte': 'male',
    'kaufmann, prof. dr.-ing. habil. michael': 'male',
    'kay gottschalk': 'unknown',
    'kellner, michael': 'male',
    'kemmer, ronja': 'female',
    'kempf, martina': 'female',
    'kersten, dr. franziska': 'female',
    'kerstin griese': 'female',
    'kerstin przygodda': 'female',
    'kerstin radomski': 'female',
    'keuter, stefan': 'male',
    'kever, rocco': 'male',
    'khan, misbah': 'unknown',
    'kiesewetter, roderich': 'male',
    'kießling, michael': 'male',
    'kippels, dr. georg': 'male',
    'klaus mack': 'male',
    'kleebank, helmut': 'male',
    'klein, dr. ottilie': 'female',
    'kleinschmidt, kurt': 'male',
    'klingbeil, lars': 'male',
    'klose, annika': 'female',
    'klöckner, julia': 'female',
    'klüssendorf, tim': 'male',
    'kneller, maximilian': 'male',
    'knodel, sieghard': 'male',
    'knoerig, axel': 'male',
    'knut abraham': 'male',
    'knuth meyer-soltau': 'male',
    'koch, heinrich': 'male',
    'koegel, jürgen': 'male',
    'kofler, dr. bärbel': 'female',
    'koller, hans': 'male',
    'komning, enrico': 'male',
    'koob, markus': 'male',
    'kopf, chantal': 'female',
    'korbach, dr. stefan': 'male',
    'korell, thomas': 'male',
    'kotré, steffen': 'male',
    'koçak, ferat': 'male',
    'kraft, dr. rainer': 'male',
    'krah, dr. maximilian': 'male',
    'kramme, anette': 'female',
    'krauthausen, manuel': 'male',
    'kreiser, dunja': 'female',
    'krichbaum, gunther': 'male',
    'krieger, lukas': 'male',
    'krings, prof. dr. günter': 'male',
    'kröber, martin': 'male',
    'kuban, tilman': 'male',
    'kurt kleinschmidt': 'male',
    'köhler, achim': 'male',
    'köktürk, cansin': 'female',
    'kölbl, daniel': 'male',
    'könig, anne': 'female',
    'könig, jörn': 'male',
    'körber, carsten': 'male',
    'körner, dr. konrad': 'male',
    'köstering, jan': 'male',
    'ladzinski, thomas': 'male',
    'lamely, pierre': 'male',
    'lamya kaddor': 'female',
    'lang, ricarda': 'female',
    'lange, ulrich': 'male',
    'lars ehm': 'male',
    'lars haise': 'male',
    'lars klingbeil': 'male',
    'lars rohwer': 'male',
    'lars schieske': 'male',
    'laschet, armin': 'male',
    'latendorf, ina': 'female',
    'launert, dr. silke': 'female',
    'lauterbach, prof. dr. karl': 'male',
    'lay, caren': 'female',
    'lea reisner': 'female',
    'lehmann, jens': 'male',
    'lehmann, sven': 'male',
    'leif erik bodin': 'male',
    'leif-erik holm': 'male',
    'lemke, sonja': 'female',
    'lemke, steffi': 'female',
    'lenhard, rebecca': 'female',
    'lensing, sascha': 'unknown',
    'lenz, dr. andreas': 'male',
    'leon eckert': 'male',
    'limbacher, esra': 'female',
    'limburg, helge': 'male',
    'linda heitmann': 'female',
    'lindh, helge': 'male',
    'lindholz, andrea': 'female',
    'linnemann, dr. carsten': 'male',
    'lips, patricia': 'female',
    'lisa badum': 'female',
    'lisa paus': 'female',
    'lisa schubert': 'female',
    'loop, denise': 'female',
    'lorenz gösta beutin': 'male',
    'lucassen, rüdiger': 'male',
    'lucks, max': 'male',
    'luczak, dr. jan-marco': 'male',
    'ludwig, daniela': 'female',
    'ludwig, dr. saskia': 'female',
    'lugk, bettina': 'female',
    'luigi pantisano': 'male',
    'luise amtsberg': 'female',
    'lukas benner': 'male',
    'lukas krieger': 'male',
    'lukas rehm': 'male',
    'luke hoß': 'male',
    'lutz brinkmann': 'male',
    'lübcke, dr. andrea': 'female',
    'lührmann, dr. anna': 'female',
    'maack, sebastian': 'male',
    'machalet, dr. tanja': 'female',
    'macit karaahmetoäÿlu': 'male',
    'mack, klaus': 'male',
    'mackensen-geis, isabel': 'female',
    'maik brückner': 'male',
    'mandy eißing': 'female',
    'manfred schiller': 'male',
    'mann, holger': 'male',
    'manuel krauthausen': 'male',
    'marc bernhard': 'male',
    'marc biadacz': 'male',
    'marc henrichmann': 'male',
    'marcel bauer': 'male',
    'marcel emmerich': 'male',
    'marcel queckemeyer': 'male',
    'marcus bühl': 'male',
    'mareike hermeier': 'female',
    'maren kaminski': 'female',
    'mark helfrich': 'male',
    'markus frohnmaier': 'male',
    'markus koob': 'male',
    'markus matzerath': 'male',
    'marlene schönberger': 'female',
    'martel, johann': 'male',
    'martin erwin renner': 'male',
    'martin gerster': 'male',
    'martin hess': 'male',
    'martin kröber': 'male',
    'martin rabanus': 'male',
    'martin reichardt': 'male',
    'martina englhardt-kopf': 'female',
    'martina kempf': 'female',
    'marvi, parsa': 'unknown',
    'marvin schulz': 'male',
    'mast, katja': 'female',
    'mattfeldt, andreas': 'male',
    'matthias david mieves': 'male',
    'matthias gastel': 'male',
    'matthias hauer': 'male',
    'matthias helferich': 'male',
    'matthias moosdorf': 'male',
    'matthias rentzsch': 'male',
    'matzerath, markus': 'male',
    'max lucks': 'male',
    'maximilian kneller': 'male',
    'mayer, andreas': 'male',
    'mayer, dr. zoe': 'female',
    'mayer, stephan': 'male',
    'mayer-lay, volker': 'male',
    'mazzi, tamara': 'female',
    'mechthild heil': 'female',
    'meiners, danny': 'unknown',
    'meiser, pascal': 'male',
    'meister, dr. michael': 'male',
    'melanie bernstein': 'female',
    'merendino, stella': 'female',
    'merz, friedrich': 'male',
    'metin hakverdi': 'male',
    'metzler, jan': 'male',
    'meyer-soltau, knuth': 'male',
    'micha fehre': 'male',
    'michael brand (fulda)': 'male',
    'michael donth': 'male',
    'michael frieser': 'male',
    'michael hose': 'male',
    'michael kellner': 'male',
    'michael kießling': 'male',
    'michael schrodi': 'male',
    'michaelsen, swantje henrike': 'female',
    'michel, kathrin': 'female',
    'middelberg, dr. mathias': 'male',
    'miersch, dr. matthias': 'male',
    'mieves, matthias david': 'male',
    'mihalic, dr. irene': 'female',
    'mijatović, boris': 'male',
    'minich, sergej': 'male',
    'mirco hanker': 'male',
    'mirow, sahra': 'female',
    'mirze edis': 'unknown',
    'misbah khan': 'unknown',
    'mixl, reinhard': 'male',
    'moll, claudia': 'female',
    'moosdorf, matthias': 'male',
    'moser, christian': 'male',
    'möller, siemtje': 'female',
    'möller, stefan': 'male',
    'müller, axel': 'male',
    'müller, carsten': 'male',
    'müller, claudia': 'female',
    'müller, florian': 'male',
    'müller, sascha': 'unknown',
    'müller, sepp': 'male',
    'münzenmaier, sebastian': 'male',
    'mützenich, dr. rolf': 'male',
    'nacke, dr. stefan': 'male',
    'nadine heselhaus': 'female',
    'nancy faeser': 'female',
    'nanni, sara': 'female',
    'nasr, rasha': 'female',
    'natalie pawlik': 'female',
    'naujok, edgar': 'male',
    'neuhäuser, charlotte antonia': 'female',
    'nick, dr. ophelia': 'female',
    'nicklas kappe': 'male',
    'nicole gohlke': 'female',
    'nicole hess': 'female',
    'nicole höchst': 'female',
    'nieland, iris': 'female',
    'nolte, jan ralf': 'male',
    'norbert maria altenkamp': 'male',
    'notz, dr. konstantin von': 'male',
    'nouripour, omid': 'male',
    'oellers, wilfried': 'male',
    'oest, florian': 'male',
    'olaf hilmer': 'male',
    'olaf scholz': 'male',
    'olav gutting': 'male',
    'oliver kaczmarek': 'male',
    'oliver pöpsel': 'male',
    'omid nouripour': 'male',
    'orthey, harald': 'male',
    'ortleb, josephine': 'female',
    'oster, josef': 'male',
    'otte, henning': 'male',
    'otte, karoline': 'female',
    'otten, gerold': 'male',
    'oßner, florian': 'male',
    'pantazis, dr. christos': 'male',
    'pantisano, luigi': 'male',
    'parsa marvi': 'unknown',
    'pascal meiser': 'male',
    'pascal reddig': 'male',
    'patricia lips': 'female',
    'patrick schnieder': 'male',
    'paul, andreas': 'male',
    'pauli, denis': 'male',
    'pauls, dr. thomas': 'male',
    'paus, lisa': 'female',
    'pawlik, natalie': 'female',
    'peick, jens': 'male',
    'pellmann, sören': 'male',
    'peter aumer': 'male',
    'peter beyer': 'male',
    'peter boehringer': 'male',
    'peter bohnhof': 'male',
    'peter felser': 'male',
    'peterka, tobias matthias': 'male',
    'philip m. a. hoffmann': 'male',
    'philipp amthor': 'male',
    'piechotta, dr. med. paula': 'female',
    'pierre lamely': 'male',
    'pilsinger, dr. med. stephan': 'male',
    'pistorius, boris': 'male',
    'ploß, dr. christoph': 'male',
    'plum, dr. martin': 'male',
    'pohlmann, jan-wilhelm': 'male',
    'polat, filiz': 'female',
    'poschmann, sabine': 'female',
    'preisendanz, dr. david': 'male',
    'prof. dr. armin grau': 'male',
    'prof. dr. günter krings': 'male',
    'prof. dr. ingo hahn': 'male',
    'prof. dr. karl lauterbach': 'male',
    'prof. dr. lars castellucci': 'male',
    'prof. dr. matthias hiller': 'male',
    'prof. dr. reza asghari': 'male',
    'prof. dr.-ing. habil. michael kaufmann': 'male',
    'protschka, stephan': 'male',
    'przygodda, kerstin': 'female',
    'pöpsel, oliver': 'male',
    'queckemeyer, marcel': 'male',
    'rabanus, martin': 'male',
    'rachel, thomas': 'male',
    'radomski, kerstin': 'female',
    'radwan, alexander': 'male',
    'raimond scheirich': 'male',
    'rainer galla': 'male',
    'rainer groß': 'male',
    'rainer, alois': 'male',
    'ralph brinkhaus': 'male',
    'ralph edelhäußer': 'male',
    'ramelow, bodo': 'male',
    'rasha nasr': 'female',
    'rathert, dr. anna': 'female',
    'raue, arne': 'male',
    'rebecca lenhard': 'female',
    'reck, christian': 'male',
    'reddig, pascal': 'male',
    'reem alabali radovan': 'female',
    'rehbaum, henning': 'male',
    'rehm, lukas': 'male',
    'reichardt, martin': 'male',
    'reichardt, truels': 'male',
    'reichel, dr. markus': 'male',
    'reichinnek, heidi': 'female',
    'reinalter, dr. anja': 'female',
    'reinhard mixl': 'male',
    'reisner, lea': 'female',
    'renner, martin erwin': 'male',
    'rentzsch, matthias': 'male',
    'rené bochmann': 'male',
    'ricarda lang': 'female',
    'rietenberg, sylvia': 'female',
    'rinkert, daniel': 'male',
    'rita schwarzelühr-sutter': 'female',
    'robin jünger': 'unknown',
    'rocco kever': 'male',
    'roderich kiesewetter': 'male',
    'rohde, dennis': 'male',
    'rohwer, lars': 'male',
    'roloff, sebastian': 'male',
    'ronald gläser': 'male',
    'ronja kemmer': 'female',
    'roth, claudia': 'female',
    'rothenberger, johannes': 'male',
    'rothfuß, dr. rainer': 'male',
    'rottwilm, dr. philipp': 'male',
    'rouenhoff, stefan': 'male',
    'ruben rupp': 'male',
    'rudolph, dr. thorsten': 'male',
    'rudzka, angela': 'female',
    'rump, daniela': 'female',
    'rupp, ruben': 'male',
    'rupprecht, albert': 'male',
    'röttgen, dr. norbert': 'male',
    'röwekamp, thomas': 'male',
    'rüdiger lucassen': 'male',
    'rüffer, corinna': 'female',
    'rützel, bernd': 'male',
    'saathoff, johann': 'male',
    'sabine dittmar': 'female',
    'sabine poschmann': 'female',
    'sahra mirow': 'female',
    'salihović, zada': 'female',
    'sanae abdi': 'female',
    'sandra carstensen': 'female',
    'santos-wintz, catarina dos': 'female',
    'sara nanni': 'female',
    'sascha lensing': 'unknown',
    'sascha müller': 'unknown',
    'sascha van beek': 'unknown',
    'saskia esken': 'female',
    'sassenrath, carl-philipp': 'male',
    'schahina gambir': 'female',
    'schattner, bernd': 'male',
    'schauws, ulle': 'female',
    'scheer, dr. nina': 'female',
    'scheirich, raimond': 'male',
    'schenderlein, dr. christiane': 'female',
    'scheurell, volker': 'male',
    'schielke-ziesing, ulrike': 'female',
    'schieske, lars': 'male',
    'schießl, carina': 'female',
    'schiller, manfred': 'male',
    'schliesing, david': 'male',
    'schmid, christoph': 'male',
    'schmid, dr. nils': 'male',
    'schmidt, dagmar': 'female',
    'schmidt, dr. paul': 'male',
    'schmidt, henri': 'male',
    'schmidt, jan wenzel': 'male',
    'schmidt, julian': 'male',
    'schmidt, sebastian': 'male',
    'schmidt, stefan': 'male',
    'schmidt, uwe': 'male',
    'schneider (erfurt), carsten': 'male',
    'schneider, julia': 'female',
    'schnieder, patrick': 'male',
    'scholz, olaf': 'male',
    'schraps, johannes': 'male',
    'schreiner, felix': 'male',
    'schrodi, michael': 'male',
    'schroeter, georg': 'male',
    'schröder, stefan': 'male',
    'schubert, lisa': 'female',
    'schuhmann, bernd': 'male',
    'schulz, marvin': 'male',
    'schulz, uwe': 'male',
    'schulze, svenja': 'female',
    'schwabe, frank': 'male',
    'schwartze, stefan': 'male',
    'schwarz, andreas': 'male',
    'schwarzelühr-sutter, rita': 'female',
    'schwerdtner, ines': 'female',
    'schäfer, dr. sebastian': 'male',
    'schäfer, jamila': 'female',
    'schätzl, johannes': 'male',
    'schönberger, marlene': 'female',
    'sebastian fiedler': 'male',
    'sebastian hartmann': 'male',
    'sebastian maack': 'male',
    'sebastian münzenmaier': 'male',
    'sebastian roloff': 'male',
    'sebastian schmidt': 'male',
    'sepp müller': 'male',
    'serap güler': 'female',
    'sergej minich': 'male',
    'sieghard knodel': 'male',
    'siemtje möller': 'female',
    'silvia breher': 'female',
    'simone borchardt': 'female',
    'simone fischer': 'female',
    'sonja eichwede': 'female',
    'sonja lemke': 'female',
    'stefan henze': 'male',
    'stefan keuter': 'male',
    'stefan möller': 'male',
    'stefan rouenhoff': 'male',
    'stefan schmidt': 'male',
    'stefan schröder': 'male',
    'stefan schwartze': 'male',
    'steffen bilger': 'male',
    'steffen janich': 'male',
    'steffen kotré': 'male',
    'steffi lemke': 'female',
    'stella merendino': 'female',
    'stephan albani': 'male',
    'stephan brandner': 'male',
    'stephan mayer': 'male',
    'stephan protschka': 'male',
    'susanne hierl': 'female',
    'sven lehmann': 'male',
    'svenja schulze': 'female',
    'swantje henrike michaelsen': 'female',
    'sylvia rietenberg': 'female',
    'sören bartol': 'male',
    'sören pellmann': 'male',
    'tamara mazzi': 'female',
    'tarek al-wazir': 'male',
    'thomas bareiß': 'male',
    'thomas dietz': 'male',
    'thomas erndl': 'male',
    'thomas fetsch': 'male',
    'thomas jarzombek': 'male',
    'thomas korell': 'male',
    'thomas ladzinski': 'male',
    'thomas rachel': 'male',
    'thomas röwekamp': 'male',
    'thorsten frei': 'male',
    'tijen ataoğlu': 'female',
    'tilman kuban': 'male',
    'tim klüssendorf': 'male',
    'timon dzienus': 'male',
    'tino chrupalla': 'male',
    'tobias ebenberger': 'male',
    'tobias matthias peterka': 'male',
    'torben braga': 'male',
    'truels reichardt': 'male',
    'udo theodor hemmelgarn': 'male',
    'ulle schauws': 'female',
    'ulrich lange': 'male',
    'ulrike schielke-ziesing': 'female',
    'uwe feiler': 'male',
    'uwe foullong': 'male',
    'uwe schmidt': 'male',
    'uwe schulz': 'male',
    'verena hubertz': 'female',
    'victoria broßart': 'female',
    'vinzenz glaser': 'male',
    'violetta bock': 'female',
    'volker mayer-lay': 'male',
    'volker scheurell': 'male',
    'wilfried oellers': 'male',
    'wilhelm gebhard': 'male',
    'wolfgang dahler': 'male',
    'zada salihović': 'female',
}
